#ifndef QUICHE_OVERRIDES_QUICHE_PLATFORM_IMPL_QUICHE_EXPORT_IMPL_H_
#define QUICHE_OVERRIDES_QUICHE_PLATFORM_IMPL_QUICHE_EXPORT_IMPL_H_

// These macros are documented in: quic/platform/api/quic_export.h
#include "build/buildflag.h"

#define QUICHE_EXPORT_IMPL
#define QUICHE_EXPORT_PRIVATE_IMPL
#define QUICHE_NO_EXPORT_IMPL

#endif  // QUICHE_OVERRIDES_QUICHE_PLATFORM_IMPL_QUICHE_EXPORT_IMPL_H_
